### ISSUE TITLE
Showing duplicate change sets

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#18] opened 2019-05-21 06:44 UTC
**Steps to reproduce:**

1. Sign In
2. Open a local repository
3. Rename a file

**Actual Result:**
Once you rename a file there are two of the same file changes are shown:
eg. Showing two README2, instead of One.

![image](https://user-images.githubusercontent.com/22312351/57657923-ca860800-7591-11e9-93ed-1db8c6548ae3.png)

**Expected Result:**
Should only show one file change

**Comment by colinwerner** [comment] 2019-05-22 04:51
The steps to reproduce are inconsistent with what I am seeing.

First of all, I cannot rename a file in visual git (issue #49)

Next, once I rename a file (git mv oldfile newfile). This is what I see:
![image](https://user-images.githubusercontent.com/15122789/58148176-8be7f180-7c12-11e9-95cd-5c201da84aed.png)

**Comment by colinwerner** [comment] 2019-05-22 21:27
Not reproducible on PC. See #47 for issues on Mac.

**Comment by sterlinglaird** [comment] 2019-05-22 23:14
James has determined this is not an issue, cannot reproduce.

**Comment by jerushachua** [comment] 2019-05-22 23:14
Confirmed as not reproducible. Closing.

**Closed** 2019-05-22 23:14 UTC
Labels: High Priority, P3, Small, Sprint 1, bug
