### ISSUE TITLE
Pulling directly after cloning a repository occasionally crashes the app

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#42] opened 2019-05-21 07:21 UTC
_NOTE: This is an intermittent issue that only occurs when cloning some repositories, it may not necessarily be reproducible._

**Steps to reproduce:**
1. Clone a repository by clicking the 'repository' button at the top
![image](https://user-images.githubusercontent.com/22312351/57647354-d49e1a00-7616-11e9-9af2-6bd8ed1dc70e.png)
2. Pull immediately after the successful clone message has been displayed

**Behaviour:**
Doing this will cause the screen to go blank and VisualGit must be restarted in order for it to work again. 

**Possible tasks:**
- Investigate the cause for the crashing
- Investigate why it only occurs on some repositories
- Make changes to fix the crashing

**Comment by colinwerner** [comment] 2019-06-18 21:41
I was unable to reproduce this issue, thus will close it.

**Closed by colinwerner** 2019-06-18 21:41 UTC
Labels: Medium, Medium priority, bug
