### ISSUE TITLE
Cloning a repository using list will sometimes crash after cloning using "Clone from internet"

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#28] opened 2019-05-21 06:59 UTC
**Steps to reproduce:**

1. login using credentials
2. clone a valid repository using "Clone from internet"
3. click on the repository name on the top left corner
4. select a repository from the list
5. click "clone $REPOSITORY_NAME"
6. the entire app will go blank/crashes

May to need to repeat steps more than once to reproduce as this will only occur once in a while.
Similar issue to issue #42 Pulling directly after cloning a repository occasionally crashes the app.

**Expected behavior:**
The app should update to show the new repository
The repository should be cloned to the local directory

**Actual behavior:**
The app goes blank
Only a folder with the repository name is created and contains a .git folder, no files are cloned

**Comment by hdauvic** [comment] 2019-06-14 20:59
Currently unreproducible. Possibly resolved.

**Comment by jerushachua** [comment] 2019-06-16 20:54
I also haven't encountered this issue. We can close this as not able to reproduce.

**Closed by jerushachua** 2019-06-16 20:54 UTC
Labels: Low Priority, Medium, bug
