### ISSUE TITLE
Pressing F5 resets the app

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#10] opened 2019-05-21 06:31 UTC
Regardless of where you are within the app, pressing F5 resets the whole app and takes you back to the login screen. This should not be possible as it may produce unexpected behavior for the rest of the app and gives the impression the app is not stable.

**Steps to reproduce:**

1. Sign in or continue without sign in on Visual Git
2. Press F5
3. Observe app reset

**Expected Output:**

F5 no longer takes you back to the login screen

**Comment by colinwerner** [comment] 2019-05-22 04:53
Is this actually a bug? Sounds like a built in feature to me, we should be able to override the F5 to be a no-op, but is that desired?

**Comment by colinwerner** [comment] 2019-05-22 21:34
We need to determine what the behaviour is for this.

Also, this would be easier if we do #19 first.

**Comment by jerushachua** [comment] 2019-05-22 22:41
This is assigned to group 2.

**Comment by trstndvll** [comment] 2019-05-24 00:06
@aeogunmuyiwa I tested your branch on my Mac as you asked, and I can confirm that fn+F5 which used to reset the app does not reset it anymore. That's awesome! I could still reset the app using command+R, so it looks like that still needs to be fixed. Hope this helps!

**Comment by aeogunmuyiwa** [comment] 2019-05-24 03:06
Thanks @trstndvll I appreciate your feedback.

**Comment by Unimax** [comment] 2019-05-24 03:25
whoever doing the testing please also test when u switch to another window (say using sift+tab and switch to chrome) and later coming back to our app it still should block all the shortcuts to refresh.

**Comment by aeogunmuyiwa** [comment] 2019-05-24 03:54
Please can someone pull the latest branch of bug-issue10. I have updated the code so it should not crash when you switch tabs and also please test the F5 and refresh short-keys. Please leave your feedback as well. Thanks.

**Comment by trstndvll** [comment] 2019-05-24 04:55
@aeogunmuyiwa  Just pulled it again and I can confirm command+R isn't working anymore. Great job guys!

**Comment by Unimax** [comment] 2019-05-24 04:58
I tested on Windows 10 & Ubuntu 18, Both Ctrl+R and F5 is no longer refreshing/Crashing the application.

**Comment by aeogunmuyiwa** [comment] 2019-05-24 05:07
Thanks @trstndvll @Unimax  for testing it out and confirming that it works properly now. I believe the issue is done , I will confirm what steps we need to take before we close the issue.

**Comment by aeogunmuyiwa** [comment] 2019-05-25 03:35
closing.

**Comment by Unimax** [comment] 2019-05-25 06:29
> closing.

just for future times, an issue is closed after merging the PR. read the wiki colin had made.
anyway good work on the issue and thanks for being there while Colin was reviewing.

**Comment by aeogunmuyiwa** [comment] 2019-05-27 18:29
I reopened the issue to remove the inappropriate log message of " registration failed" when the app starts up and attempts to register the shortcut keys. Can someone not in group2  please review the changes thanks

**Comment by aeogunmuyiwa** [comment] 2019-05-27 21:56
Changes approved , all changes merged and the issue is closed.

**Closed by aeogunmuyiwa** 2019-05-27 21:56 UTC
Labels: Group2, High Priority, P4, Small, Sprint 1, bug
