### ISSUE TITLE
Issue with selecting folder when cloning -Path Does not Exist

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#26] opened 2019-05-21 06:56 UTC
**Steps to reproduce**

1. Click on Save without any URL
![image](https://user-images.githubusercontent.com/22312351/57658580-56992f00-7594-11e9-9254-461f243f77a7.png)

2. It will give a pop up message saying "Clone Failed" close it
![image](https://user-images.githubusercontent.com/22312351/57658609-703a7680-7594-11e9-9e9a-9f40b8da8aa7.png)

3. Go back to the main screen and click on clone again in the same folder. (You get this error)

![image](https://user-images.githubusercontent.com/22312351/57658624-76c8ee00-7594-11e9-9638-58293a24497a.png)

But if you choose a different folder it does not give you that error

**Comment by Athenasko** [comment] 2019-05-22 06:09
Steps for Reproduction (Differ slightly from above as it seems new functionality has been added since then):

My steps:
1. Click Browse button beside "File location to save to".
2. Select a folder to save to.
3. Close pop-up telling you to enter repository URL to clone.
4. Click Browse button again.
5. Click "Select folder" without changing anything.

Expected Results:
1. If no repository URL is entered, prompt should appear again to enter URL to clone from.
2. If repository URL is entered, file location should appear.

Actual Results:
"Path Does Not Exist. Check path again." error alert appears.

**Comment by jerushachua** [comment] 2019-05-22 22:42
This issue is assigned to group 4.

**Comment by jpstoldt** [comment] 2019-05-26 22:23
After further analysis, we have identified the underlying issue as a bug in Electron which affects all directory selection dialogs using the INPUT TYPE=FILE html tag in the application. Options to resolve are 1) change the user interface flow of the application to avoid the issue, however this would result in a loss of current application functionality; 2) replace uses of INPUT TYPE=FILE tag with a native system dialog function in Electron which does not have the issue; 3) upgrade Electron to its latest version which contains a bug fix to the issue.

**Closed** 2019-05-28 21:17 UTC
Labels: Group4, High Priority, P8, Small, Sprint 1, bug
