### ISSUE TITLE
Making a commit through visual git does not cause the graph to update

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#7] opened 2019-05-21 06:27 UTC
Making a commit through visual git does not cause the graph to update.

**Steps to reproduce:**

1. Make local changes
2. Stage and commit the changes.

**Actual behavior:** Node graph doesn't update

**Expected behavior:** Node graph should now contain the new commit

**Comment by colinwerner** [comment] 2019-05-22 04:34
I cannot even get VisualGit to stage changes :(.

I created issue #47, thus this issue is dependent on #47.

**Comment by sterlinglaird** [comment] 2019-05-22 12:55
@colinwerner for what it's worth I get the same behavior as Omar. Perhaps there is something else stopping changes from showing up in your environment (or a separate bug) ?

**Comment by colinwerner** [comment] 2019-05-22 16:11
I don't actually think Omar reproduced this issue, I believe they were from a previous fork.

@sterlinglaird what platform are you running (Windows, OSX, or Linux)?

**Comment by sterlinglaird** [comment] 2019-05-22 16:56
I'm running windows 10. On my machine VisualGit has no problem recognizing changed files.

**Comment by jerushachua** [comment] 2019-05-22 22:38
This is being pushed out of sprint 1 because it is dependent on https://github.com/uvicgse/project-virtual-team-1/issues/47

**Comment by trstndvll** [comment] 2019-05-30 20:55
Issue seems to be stemming from git.ts, in function addAndCommit(). The function clearSelectAllCheckbox() is being called and is stopping the graph from being updated. Once this issue is resolved and pushed to master, we will open a branch for #70 since it's dependent.

**Comment by aeogunmuyiwa** [comment] 2019-05-30 21:49
So i removed the clearSelectAllCheckbox() and clearCommitMessage() functions because they are not implemented anywhere in the application, they seem like functions that are trying to manipulate the html properties but are never used or implemented

**Comment by trstndvll** [comment] 2019-06-05 02:43
Branch "issue-7-update-graph-after-commit" merged. Closing.

**Closed by trstndvll** 2019-06-05 02:43 UTC
Labels: Group2, High Priority, Small, Sprint 2, bug
